### ISSUE TITLE
City of Wagga Wagga - replaced scraper

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#1016]
This issue has been **automatically** created by PlanningAlerts. Only close this issue once the authority is working again on PlanningAlerts.

**Comment by ianheggie** [comment]
@katska - The existing url bring up a "we have moved" page that redirects to a broken url (two slashes). The displayed url also also errors out. The [council site](https://wagga.nsw.gov.au/the-council/forms-and-applications) says lodge using NSW Planning Portal but it appears it doesn't have any data for Wagga Wagga! :(

Will you follow up with the council?

```
Online lodgement of planning applications

On 1 July 2021, important changes came into effect which change the way you lodge planning applications with Council.

Within the Wagga Wagga region, the following application types are now required to be lodged through the [NSW Planning Portal](https://www.planningportal.nsw.gov.au/).

    Development Applications
    Complying Development Certificates
    Construction Certificates
    Section 68 (Local Government Act) Applications

Hardcopy applications are no longer accepted at Council’s Customer Service.

For more information, visit our [Application Lodgement](https://wagga.nsw.gov.au/building-and-development/Applying-for-Development) page.
```

```
Resource Moved

The resource located at https://eservices.wagga.nsw.gov.au/T1PRWeb/eProperty has moved.

If not automatically redirected, please click the link below:
[https://wagga-web.t1cloud.com/T1PRDefault/WebApps/eProperty/T1PRWeb/eProperty](https://wagga-web.t1cloud.com/T1PRDefault/WebApps/eProperty//T1PRWeb/eProperty)
```
After redirection the error is:
```
Error Displaying Page

An error has occurred while processing your request,
please attempt to [Go Back](javascript:history.back();) and retry the operation.
```

**Comment by katska** [comment]
@ianheggie ok I see you're still testing as a tech one scraper so reapplying that label.

**Comment by ianheggie-oaf** [comment]
@katska - @mlandauer mentioned he has work he needs to do when I remove it from the scraper (and thus separate PR)  - so I have instead added a flag that stops an error being raised on known bad sites (but raises an error if the known bad site suddenly starts working) - this way when morph says there is an error, it actually means there is something for me to address and am sending him that as a PR - so it sits somewhere in active code - it can be pulled out when there is a viable replacement (my guess of how you want it done @mlandauer).

@mlandauer - you can set a variable to choose what is flagged as expected to be bad if you disagree with my choice and/or something else goes so bad the issue was/is flagged blocked.

@katska - I am happy for the dual labels  "technology one" and "nsw planning portal" as it reflects the reality of the code base at this time.

FYI - the nsw portal doesn't appear to have records for wagga, so creating a new scraper wont help for wagga, though it should for others. [So I think it deserved "blocked" not "in progress" label]

**Comment by ianheggie-oaf** [comment]
@jamezpolley - Update as of 21 May 2025 - I can see **some, but not enough** flowing through the NSW portal:

* Under Assessment - https://www.planningportal.nsw.gov.au/ppr/under%20assessment - 1 result when filtered by Wagga Wagga LGA ("Proposals that are still under assessment can be access for public viewing here. ")

* Pre-Exhibition - 1 result when filtered https://www.planningportal.nsw.gov.au/ppr/pre-exhibition?field_ppr_local_government_value=WAGGA+WAGGA&title= ("Details of Planning Proposals within the pre-exhibition phase are available here. ")

* On Exhibition - 0 results https://www.planningportal.nsw.gov.au/ppr/under%20exhibition?field_ppr_local_government_value=WAGGA+WAGGA&title=&field_exhibition_start_date_value=&field_exhibition_end_date_value= ("Planning Proposals that are available for public inspection and comment are available here. ")

Given https://www.planningalerts.org.au/authorities/wagga_wagga  has a median of 43 per week, and assuming the query should show us att least 2 weeks worth of applications, these numbers are statistically VERY unlikely (you are more likely to win Tattslotto 15 weeks in a row without cheating!)

**Comment by katska** [comment]
@ianheggie-oaf If this becomes something to bring up with council again please comment and assign me.

**Comment by ianheggie-oaf** [comment]
@katska - my best guess  of how to proceed is to contact the council to 
* confirm if the few results above are what they expect (as its significantly less than expected),  and
* that there is no better way of obtaining the information. 

That will then help us plan how we proceed.

FYI - as of 26 May 2025, 2:26AM, there are:
* 1 result for [Under assesment](https://www.planningportal.nsw.gov.au/ppr/under%20assessment?field_ppr_local_government_value=WAGGA+WAGGA&title=)
* 1 result for [Under exhibition](https://www.planningportal.nsw.gov.au/ppr/under%20exhibition?field_ppr_local_government_value=WAGGA+WAGGA&title=&field_exhibition_start_date_value=&field_exhibition_end_date_value=) "Part 11 Farrer Road, Boorooma", which is also is listed on the council's [Public Exhibitions](https://wagga.nsw.gov.au/the-council/planning-and-reporting/public-exhibitions) page and appears to be a council initiative
* no results for [Pre-Exhibition](https://www.planningportal.nsw.gov.au/ppr/pre-exhibition?field_ppr_local_government_value=WAGGA+WAGGA&title=)

Footer has a link [APIs for Digital Services](https://www.planningportal.nsw.gov.au/API) which may be of interest rather than scraping pages

**Comment by ianheggie-oaf** [comment]
Confirmed still down when using plannies-mate as proxy:
```
Collecting feed data for wagga...
wagga: ERROR: Couldn't find table
/app/lib/technology_one_scraper/page/index.rb:23:in `scrape'
/app/lib/technology_one_scraper.rb:70:in `scrape_period'
/app/lib/technology_one_scraper.rb:18:in `scrape'
scraper.rb:20:in `block in scrape'
scraper.rb:16:in `each'
scraper.rb:16:in `scrape'
scraper.rb:49:in `run'
scraper.rb:70:in `<main>'
```

**Comment by ianheggie-oaf** [comment]
Spec work:

Removed from multiple_technology_one scraper as the council isnt using t1 formatted pages

Looks like multiple_div_cards would be a suitable scraper IF it wasn't behind cloudflare! It at least requires ajax to pull in the data.

AHH - Just found a api call that isnt behind cloudflare!

```
curl 'https://data.wagga.nsw.gov.au/tech1/api/public/application/exhibitiondocs' \
  -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:149.0) Gecko/20100101 Firefox/149.0' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-AU,en-GB;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Accept-Encoding: gzip, deflate, br, zstd' \
  -H 'Referer: https://wagga.nsw.gov.au/' \
  -H 'Origin: https://wagga.nsw.gov.au' \
  -H 'Connection: keep-alive' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Priority: u=4' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' > ,curl.json
```

Returns nice json - and the info_url is simple, eg: `https://data.wagga.nsw.gov.au/tech1/api/public/ecm/folder/6898510`
```json
{
  "success": true,
  "message": "",
  "data": {
    "advertisedDevelopment": [
      {
        "type": "Advertised",
        "number": "DA26/0130",
        "processID": 474731,
        "address": "1A Moorong St MOORONG NSW 2650",
        "endDate": "21/04/2026",
        "publishedDocuments": [
          {
            "docSetID": 6898510,
            "date": "2026-04-01T14:48:28",
            "description": "Documents Notified & Advertised - *Publish*",
            "exhibitionType": 0,
            "precis": "DA26/0130 - Exhibition Documents",
            "relationship": null,
            "fileSize": 4.44
          }
        ]
      }
    ],
    "notifiedDevelopment": [
      {
        "type": "Notified",
        "number": "DA26/0126",
        "processID": 474518,
        "address": "6 Scarborough Way GUMLY GUMLY NSW 2652",
        "endDate": "10/04/2026",
        "publishedDocuments": [
          {
            "docSetID": 6886791,
            "date": "2026-03-17T16:20:23",
            "description": "Documents Notified - *Publish*",
            "exhibitionType": 0,
            "precis": "DA26/0126 - Exhibition Documents",
            "relationship": null,
            "fileSize": 1.45
          }
        ]
      },
...
```

https://wagga.nsw.gov.au/the-council/planning-and-reporting/public-exhibitions

**Comment by ianheggie-oaf** [comment]
Spec work:

Update PA entry for new private wagga_wagga scraper

NOTE: There is no description listed, and the info_link is to the submitted pdf. The following description is used instead, based on their web page:

```ruby
        description = if entry["type"] == "Advertised"
                        "Advertised Development Applications on exhibition with broader public interest"
                      else
                        "Development Applications on exhibition - notified adjoining or near to the development parties"
                      end
```
