### ISSUE TITLE
City of Ryde

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#1024]
This issue has been **automatically** created by PlanningAlerts. Only close this issue once the authority is working again on PlanningAlerts.

**Comment by katska** [comment]
Morph error includes a Timeout. First question is it dead, a benign error or blocked? 

Note also errors thread between other output, which can be confusing, so I take a best guess as in this case that the error continues after beginning the next one (Shellharbour)

Collecting feed data for ryde...

ryde: ERROR: execution expired
Collecting feed data for shellharbour...
/app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
/app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:937:in `open'
/app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
/app/vendor/ruby-2.5.8/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:935:in `connect'
/app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/app/vendor/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:915:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:655:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:595:in `connection_for'
/app/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:885:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.7/lib/mechanize/http/agent.rb:280:in `fetch'
/app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.7/lib/mechanize.rb:464:in `get'
/app/lib/technology_one_scraper.rb:67:in `scrape_period'
/app/lib/technology_one_scraper.rb:18:in `scrape'

**Comment by katska** [comment]
DAs no longer at https://eservices.ryde.nsw.gov.au/T1PRProd/WebApps/eProperty

Moved to https://ryde-web.t1cloud.com/T1PRDefault/WebApps/eProperty/P1/PublicNotices/AllPublicNotices.aspx?r=COR.P1.WEBGUEST&f=COR.ESB.PUBNOTAL.ENQ

listed in
 https://github.com/planningalerts-scrapers/multiple_technology_one/blob/master/lib/technology_one_scraper/authorities.rb

**Comment by katska** [comment]
Looks like they may have just moved the data to T1 cloud

try replacing https://eservices.ryde.nsw.gov.au/T1PRProd/WebApps/eProperty

with https://ryde-web.t1cloud.com/T1PRDefault/WebApps/eProperty

at line 112 of https://github.com/planningalerts-scrapers/multiple_technology_one/blob/master/lib/technology_one_scraper/authorities.rb

**Comment by katska** [comment]
ok slightly weird aside. another check to see  if old DAs will be visible on the new site if they've moved (and thus also likely same path structure/same data organisation & DA publishing system). So I go to a DA already on Planning Alerts, click through to 'view source' and look at a full path of a recent/ish DA. I'll then replace the head of the path with what I understand to be the new location (eg as above). In this case. 'view source' at planning alerts DA from 2 months ago redirects to
https://lngnoticeboard.onegov.nsw.gov.au/searchresult/details/SR0001346897
which sat doing expressly nothing. I gave it about a minute, but it's a silent hang (maybe a more descriptive term. Dead URL bar, no loading status update, error code, other feedback nor website)

**Comment by ianheggie** [comment]
@katska - FYI - it does appear that they have changed the server hosting but not the software - I am testing the fix now on morph.io

**Comment by ianheggie-oaf** [comment]
@katska - Test passed and so I have raised a PR - please assign this issue to @mlandauer  [DONE]

**Comment by jamezpolley** [comment]
Most recent run shows no errors for Ryde:

```
scraper.rb:41:in `<main>': There were errors with the following authorities: [:corangamite, :kuringgai, :mornington_peninsula, :sutherland, :wagga, :wyndham, :yarra]. See earlier output for details (RuntimeError)
```

**Comment by jamezpolley** [comment]
https://www.planningalerts.org.au/applications/3295470
