### ISSUE TITLE
City of South Perth: No data received since  1 Aug 2019

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#152]
This issue has been **automatically** created by PlanningAlerts for [City of South Perth](http://www.planningalerts.org.au/authorities/south_perth)

It uses the scraper [planningalerts-scrapers/multiple_civica](https://morph.io/planningalerts-scrapers/multiple_civica)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

**Comment by mlandauer** [comment]
Scraper output is:
```
south_perth: ERROR: undefined method `dateFrom=' for nil:NilClass
/app/lib/civica_scraper/page/search.rb:10:in `period'
/app/lib/civica_scraper.rb:54:in `scrape_period'
/app/lib/civica_scraper.rb:23:in `scrape'
```

So, looks like it might be a simple fix too.

**Comment by mlandauer** [comment]
Okay it looks like they've disabled all the DA search functionality other than just listing the advertised development applications. Oh joy.
