### ISSUE TITLE
Error on certain records

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/issues#27]
https://morph.io/planningalerts-scrapers/Brimbank_City_Council - parses some records; then fails with:
```
scraper.rb:14:in `block (2 levels) in <main>': undefined method `attributes' for nil:NilClass (NoMethodError)
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
 	from scraper.rb:9:in `block in <main>'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
 	from /app/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
 	from scraper.rb:8:in `<main>'
```

**Comment by mlandauer** [comment]
This doesn't seem to be happening now. So, closing.
