### ISSUE TITLE
PDF - undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/issues#31]
```
scraper.rb:19:in `block (2 levels) in <main>' : undefined method `split' for nil:NilClass (NoMethodError)
    from scraper.rb:12:in `each'
    from scraper.rb:12:in `block in <main>'
    from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:239:in `block in each'
    from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `upto'
    from /app/vendor/bundle/ruby/1.9.1/gems/nokogiri-1.5.0/lib/nokogiri/xml/node_set.rb:238:in `each'
    from scraper.rb:11:in `<main>'
```

**Comment by mlandauer** [comment]
Duplicate of #77
