### ISSUE TITLE
South Australia Scraper is failing

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#823]
I'm not sure why I don't see another issue here for this as it's not been gathering data for so long, but anyhoo

Here's the error when morph runs this one:
```

 Injecting scraper and running...
 /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:329:in `fetch': 429 => Net::HTTPTooManyRequests for https://cdn.plan.sa.gov.au/public-notifications/getpublicnoticessummary -- unhandled response (Mechanize::ResponseCodeError)
 	from /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:998:in `response_redirect'
 	from /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:321:in `fetch'
 	from /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.6/lib/mechanize.rb:1323:in `post_form'
 	from /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.6/lib/mechanize.rb:536:in `post'
 	from scraper.rb:9:in `<main>'
```

I can get to the URL noted https://cdn.plan.sa.gov.au/public-notifications/getpublicnoticessummary in the browser just fine.

@mlandauer it's a big one, please can you take a look next time you're in scraper-land?

**Comment by katska** [comment]
#824 duplicates this one.

**Comment by jamezpolley** [comment]
Duplicate of #824
